### ISSUE TITLE
error ni bang 

### ISSUE THREAD

**Issue by juliannizah** [imamrasyid/darkblowV42_Website#3]
Parse error: syntax error, unexpected 'print' (T_PRINT), expecting identifier (T_STRING) in E:\Xampp\htdocs\webpb-ci3\application\controllers\adm\Vouchermanagement.php on line 475
A PHP Error was encountered
Severity: Parsing Error

Message: syntax error, unexpected 'print' (T_PRINT), expecting identifier (T_STRING)

Filename: adm/Vouchermanagement.php

Line Number: 475

Backtrace:

**Comment by imamrasyid** [comment]
Sertakan SS jika tersedia.

**Comment by juliannizah** [comment]
> Sertakan SS jika tersedia.
![untitled](https://user-images.githubusercontent.com/85738429/141342464-8d991665-609b-4450-a4b7-7485a4ea0846.JPG)
voucher management erro bang di admin panel.

**Comment by imamrasyid** [comment]
di perangkat saya tidak ada masalah, silahkan bisa dicoba lagi.
jika tetap bermasalah disarankan untuk mengunduh ulang repository ini
