### ISSUE TITLE
rank clan

### ISSUE THREAD

**Issue by taxarn** [imamrasyid/darkblowV42_Website#6]
error saat membuka rank clan

Fatal error: Call to undefined method Main_protect::SessionProtect() in C:\xampp1\htdocs\application\controllers\Clan_rank.php on line 23

**Comment by taxarn** [comment]
![err-clan](https://user-images.githubusercontent.com/105220734/167421949-c03ce310-1468-463b-a1d4-14091ad8a1ef.jpg)

**Comment by imamrasyid** [comment]
Silahkan untuk mengunduh ulang repo ini
Atau anda dapat menonton tutorial pemasangan website ini di https://youtu.be/1h9E3Rdhkv0

**Comment by taxarn** [comment]
thankssss

ini voucher management sama rankup event msi blm bisa ya
![rankup error](https://user-images.githubusercontent.com/105220734/167519651-495d343b-cfc5-42fa-9cf6-23d2b6bd1668.jpg)
![voucher management](https://user-images.githubusercontent.com/105220734/167519668-f4ed0457-2022-40f6-a999-1a2a3bbb7642.jpg)
h
